### ISSUE TITLE
Mismatched free() / delete / delete [] in TextField::setIgnoredKey()

### ISSUE THREAD

**Issue by hexagonrecursion** [twohoursonelife/OneLife#188]
In is [undefined behaviour](https://isocpp.org/wiki/faq/freestore-mgmt#mixing-malloc-and-delete) to use delete or delete[] (C++ operators) to free memory allocated via malloc() (or other C library functions such as strdup() )

May I clean things up a bit and start replacing char* with std::string (because it is easier to use correctly)?

Error report from valgrind

```
==14772== Mismatched free() / delete / delete []
==14772==    at 0x484965B: operator delete[](void*) (vg_replace_malloc.c:1103)
==14772==    by 0x20DAD4: TextField::setIgnoredKey(unsigned char) (TextField.cpp:1193)
==14772==    by 0x2683E5: Picker::setIgnoredKey(unsigned char) (Picker.cpp:366)
==14772==    by 0x1B7BC3: LivingLifePage::LivingLifePage() (LivingLifePage.cpp:2504)
==14772==    by 0x174726: drawFrame(char) (game.cpp:1997)
==14772==    by 0x2B058B: GameSceneHandler::drawScene() (gameSDL.cpp:3169)
==14772==    by 0x27C2CF: callbackDisplay() (ScreenGL_SDL.cpp:2932)
==14772==    by 0x27AA5B: ScreenGL::start() (ScreenGL_SDL.cpp:2136)
==14772==    by 0x2AEF9B: mainFunction(int, char**) (gameSDL.cpp:2488)
==14772==    by 0x2AA4AF: main (gameSDL.cpp:23)
==14772==  Address 0x380dc460 is 0 bytes inside a block of size 2 alloc'd
==14772==    at 0x484586F: malloc (vg_replace_malloc.c:381)
==14772==    by 0x4D8A78D: strdup (strdup.c:42)
==14772==    by 0x20DAF7: TextField::setIgnoredKey(unsigned char) (TextField.cpp:1196)
==14772==    by 0x2683E5: Picker::setIgnoredKey(unsigned char) (Picker.cpp:366)
==14772==    by 0x1B7BA9: LivingLifePage::LivingLifePage() (LivingLifePage.cpp:2503)
==14772==    by 0x174726: drawFrame(char) (game.cpp:1997)
==14772==    by 0x2B058B: GameSceneHandler::drawScene() (gameSDL.cpp:3169)
==14772==    by 0x27C2CF: callbackDisplay() (ScreenGL_SDL.cpp:2932)
==14772==    by 0x27AA5B: ScreenGL::start() (ScreenGL_SDL.cpp:2136)
==14772==    by 0x2AEF9B: mainFunction(int, char**) (gameSDL.cpp:2488)
==14772==    by 0x2AA4AF: main (gameSDL.cpp:23)
```

**Comment by risvh** [comment]
Thanks for spotting that! However the whole code base of the parent game OHOL uses `char*` and other non-std constructs in the "game engine" called [minorGems](https://github.com/twohoursonelife/minorGems) by the original author Jason (for example, `SimpleVector` is used in place of `std::vector`), it is too huge a change to replace everything with `std::string` and it is undesirable for backward compatibility. (Unless it is a more "stand-alone" feature like Seed Spawn or Password Door, both are more 2HOL features)

In the current issue, I should really have used another way to push a new char into the variable `mForbiddenChars` in the function `setIgnoredKey` instead of using `std::string` in my change https://github.com/twohoursonelife/OneLife/commit/9980e746e9e66f5cf939b69d45adaa78f6e96236

If you are familiar with Jason's code, you're welcome to fix my change above, doing it "Jason's way", maybe use `SimpleVector` to do the `push_back` then use [`getElementString`](https://github.com/twohoursonelife/minorGems/blob/fcbe632b67226c50f3cc5baa1b6d0ae73ba698d4/util/SimpleVector.h#L194) to get back the `mForbiddenChars` in `char*`.

Also you're welcome to keep reporting this kind of issues, we're on the hunt for these kind of bugs! Thanks a lot!

**Comment by connorhsm** [comment]
@hexagonrecursion Any follow up for this?
