### ISSUE TITLE
Wrong sprites for use dummy objects

### ISSUE THREAD

**Issue by risvh** [twohoursonelife/OneLife#5]
#2 
This merge caused some use dummy objects (tools and stackable items for example) to be drawn with the wrong sprites. Reverting the change in this line (linked below) does fix the problem, probably a bad fix tho without knowing what actually caused the bug.

https://github.com/twohoursonelife/OneLife/commit/a5562af18431300db56507c327dd77b60b837e37#diff-f95b96883041b8b926e300c9b58f9e8aR2506

**Comment by connorhsm** [comment]
I suspect this change, which breaks something in current 2HOL, would have more of a purpose when we merge more of the OHOL changes since Aug 2019.
I think it will be fine to revert this specific line for this case.

@Adk9p Please comment if you have anything to add.

@risvh Are you able to submit a pull request? Make sure to tag this issue in the commit.

**Comment by risvh** [comment]
Further testing shows that the line will work with new data on the server. So the wrong sprites and the client crashes Adk and I have encountered probably is a result of testing client compiled from new code and data with live version server which is from the old code and data.

I am closing this issue, no action is required.

**Comment by risvh** [comment]
Reopening this. Although new server does work with new client fine, we want the new server to be compatible with old modded clients. (New and old here refer to the change in object auto-generation in objectBank.cpp in the OneLife repo instead of OneLifeData7).
